#! /bin/sh

sxhkd &
## Launchers
picom -bc
$HOME/.fehbg &
xsetroot -cursor_name left_ptr &
/usr/bin/dunst &
/usr/lib/polkit-kde-authentication-agent-1 &
$HOME/.config/polybar/launch.sh &
if [ ! -s $HOME/.config/mpd/pid ]; then
	mpd
fi
aria2c --enable-rpc --rpc-listen-all &
bash $HOME/.local/bin/dyndns.sh &
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Onboard state=floating
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

##
## mouse config
##
bspc config focus_follows_pointer true

# mouse key 1 moves windows
bspc config pointer_action1 move

# mouse key 2 resizes by sides 
bspc config pointer_action2 resize_side

#mouse key 3 resizes by corners
bspc config pointer_action3 resize_corner
