alias printer='sudo systemctl start org.cups.cupsd.service'
alias rpdev='python $HOME/.local/bin/renpydev.py'
alias unren='bash $HOME/.local/bin/unren.sh "${PWD}"'
alias myip='python $HOME/.local/bin/myip.py'
alias crymnt='cryfs $HOME/nextcloud/webo/keychain/keyring $HOME/syncthing/keyring'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
